version: "3"

services:
  mautic:
    restart: ${RESTART_CONDITION}
    image: mautic/mautic
    depends_on:
      - mysql
    ports:
      - "80:80"
    environment:
      MAUTIC_DB_HOST: ${MAUTIC_DB_HOST}
      MAUTIC_DB_USER: ${MAUTIC_DB_USER}
      MAUTIC_DB_PASSWORD: ${MAUTIC_DB_PASSWORD}
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0
    volumes:
      - mautic-web:/var/www/html
    networks:
      - mautic-network

  mysql:
    restart: ${RESTART_CONDITION}
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MAUTIC_DB_USER}
      MYSQL_PASSWORD: ${MAUTIC_DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mautic-network

  nginx:
    restart: ${RESTART_CONDITION}
    image: nginx:1.19
    ports:
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./conf/sslcerts:/etc/ssl/private
    depends_on:
      - mautic
    networks:
      - mautic-network

networks:
  mautic-network:
volumes:
  mautic-web:
  sslcerts:
  mysql: